version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - hasura_demo_db_data:/var/lib/postgresql/data
    env_file: ./postgres/.env
  hasura:
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file: ./hasura/.env
    build: ./hasura
volumes:
  hasura_demo_db_data:
